version: '3'
services:
  spring-boot-app:
      build:
        context: ./spring-boot-docker-master/spring-boot-docker-master/spring-boot-app
        dockerfile: Dockerfile
      ports:
        - "8080:8080"

  react-app:
      build:
        context: ./frontend/my-app
        dockerfile: Dockerfile
      ports:
        - "3000:80"